project_id              = "project-6a06b82f-4814-4b4c-b83"
region                  = "us-central1"
pool_id                 = "github-actions-pool-v5"
provider_id             = "github-provider-v5"
github_repository_owner = "staocubee"
service_account_email   = "techbeingsa@project-6a06b82f-4814-4b4c-b83.iam.gserviceaccount.com"